name=input("WHAT IS YOUR NAME  =   ")
print("Good Morning", name)
print("SIMPLE CALCULATOR")
a=int (input("a>>>         "))
b=int (input("b>>>         "))
print("ADDITION")
print(a+b)
print("SUBTRACTION")
print(a-b)
print("MULTIPLICATION")
print(a*b)
print("DIVISION")
print(a/b)